-- DROP SCHEMA stock_exchange;

CREATE SCHEMA stock_exchange AUTHORIZATION postgres;

-- DROP SEQUENCE stock_exchange.adjusted_prices_id_seq;

CREATE SEQUENCE stock_exchange.adjusted_prices_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE stock_exchange.stock_id_seq;

CREATE SEQUENCE stock_exchange.stock_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- stock_exchange.stock definition

-- Drop table

-- DROP TABLE stock_exchange.stock;

CREATE TABLE stock_exchange.stock (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ticker varchar NOT NULL,
	CONSTRAINT stock_pk PRIMARY KEY (id)
);


-- stock_exchange.adjusted_prices definition

-- Drop table

-- DROP TABLE stock_exchange.adjusted_prices;

CREATE TABLE stock_exchange.adjusted_prices (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	stock_id int4 NOT NULL,
	price int4 NULL,
	"open" int4 NULL,
	high int4 NULL,
	low int4 NULL,
	volume float8 NULL,
	"change" float8 NULL,
	"date" date NOT NULL,
	CONSTRAINT adjusted_prices_pk PRIMARY KEY (id),
	CONSTRAINT adjusted_prices_fk FOREIGN KEY (stock_id) REFERENCES stock_exchange.stock(id) ON DELETE CASCADE ON UPDATE CASCADE
);
